// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_contact_info_default = defineTool({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return Rays Academy Bhopal contact details: phone, WhatsApp, Instagram, address, and website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            name: "Rays Academy Bhopal",
            established: 2006,
            phone: "+91 7024057876",
            whatsapp: "+91 7024057876",
            instagram: "@raysacademybhopal",
            address: "Gufa Mandir Road, Lalghati, Bhopal, Madhya Pradesh",
            website: "https://www.raysacademybhopal.in/"
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/tools/list-courses.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var COURSES = [
  { slug: "class-6-8", name: "Classes 6-8 Foundation", url: "https://www.raysacademybhopal.in/courses/class-6-8" },
  { slug: "class-9", name: "Class 9", url: "https://www.raysacademybhopal.in/courses/class-9" },
  { slug: "class-10", name: "Class 10 (Board)", url: "https://www.raysacademybhopal.in/courses/class-10" },
  { slug: "class-11", name: "Class 11", url: "https://www.raysacademybhopal.in/courses/class-11" },
  { slug: "class-12", name: "Class 12 (Board)", url: "https://www.raysacademybhopal.in/courses/class-12" },
  { slug: "iit-jee", name: "IIT-JEE Coaching", url: "https://www.raysacademybhopal.in/iit-jee-coaching-bhopal" },
  { slug: "neet", name: "NEET Coaching", url: "https://www.raysacademybhopal.in/neet-coaching-bhopal" },
  { slug: "nda", name: "NDA Coaching", url: "https://www.raysacademybhopal.in/nda-coaching-bhopal" },
  { slug: "cuet", name: "CUET Coaching", url: "https://www.raysacademybhopal.in/cuet-coaching-bhopal" }
];
var list_courses_default = defineTool2({
  name: "list_courses",
  title: "List courses",
  description: "List all courses offered by Rays Academy Bhopal with their dedicated page URLs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(COURSES, null, 2) }],
    structuredContent: { courses: COURSES }
  })
});

// src/lib/mcp/tools/get-announcements.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_announcements_default = defineTool3({
  name: "get_announcements",
  title: "Get announcements",
  description: "Return currently active announcements published by Rays Academy Bhopal.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async () => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("announcements").select("title, content, priority, start_date, end_date").eq("is_active", true).order("priority", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { announcements: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "rays-academy-mcp",
  title: "Rays Academy Bhopal",
  version: "0.1.0",
  instructions: "Tools to look up information about Rays Academy Bhopal \u2014 contact details, courses offered (Classes 6-12, IIT-JEE, NEET, NDA, CUET), and active announcements.",
  tools: [get_contact_info_default, list_courses_default, get_announcements_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
